print()
print("\033[1;32;40m Renkli yazı  \n")
print(" ╔═════════════════════╗")
print(" ║    OYUNLAR MENÜSÜ   ║")
print(" ╠═════════════════════╣")
print(" ║  1-Yılan            ║")
print(" ║  2-Tetris           ║")
print(" ║  3-Adam asmaca      ║")
print(" ║  4-                 ║")
print(" ║   Seçiminiz?        ║")
print(" ╚═════════════════════╝")