print()
print("\033[1;32;40m Renkli yazı  \n")
print(" ╔═════════════════════╗")
print(" ║    ÇİZİMLER         ║")
print(" ╠═════════════════════╣")
print(" ║  1-Kare             ║")
print(" ║  2-Üçgen            ║")
print(" ║  3-Desen            ║")
print(" ║  4-                 ║")
print(" ║   Seçiminiz?        ║")
print(" ╚═════════════════════╝")